{
	"ID": "202412-17",
	"Title": "idna: Denial of Service",
	"Synopsis": "A vulnerability has been discovered in idna, which can lead to a denial of service.",
	"Product": {
		"Text": "idna",
		"Type": "ebuild"
	},
	"Announced": "2024-12-11",
	"Revised": {
		"Text": "2024-12-11",
		"Count": "1"
	},
	"Bug": [
		"929208"
	],
	"Access": "local",
	"Affected": {
		"Package": [
			{
				"Name": "dev-python/idna",
				"Auto": "yes",
				"Arch": "*",
				"Unaffected": [
					{
						"Text": "3.7",
						"Range": "ge",
						"Slot": ""
					}
				],
				"Vulnerable": [
					{
						"Text": "3.7",
						"Range": "lt",
						"Slot": ""
					}
				]
			}
		],
		"Service": {
			"Text": "",
			"Type": "",
			"Fixed": ""
		}
	},
	"Background": {
		"Text": "\n        <p>Internationalized Domain Names for Python (IDNA 2008 and UTS #46)</p>\n    "
	},
	"Description": {
		"Text": "\n        <p>A vulnerability has been discovered in idna. Please review the CVE identifier referenced below for details.</p>\n    "
	},
	"Impact": {
		"Type": "normal",
		"Text": "\n        <p>Please review the referenced CVE identifier for details.</p>\n    "
	},
	"Workaround": {
		"Text": "\n        <p>There is no known workaround at this time.</p>\n    "
	},
	"Resolution": {
		"Text": "\n        \n        \n        \n    ",
		"P": [
			{
				"Text": "All idna users should upgrade to the latest version:",
				"URI": {
					"Text": "",
					"Link": ""
				},
				"Br": null,
				"I": null,
				"Code": "",
				"P": ""
			}
		],
		"Code": [
			"\n          # emerge --sync\n          # emerge --ask --oneshot --verbose \">=dev-python/idna-3.7\"\n        "
		]
	},
	"References": {
		"URI": [
			{
				"Text": "CVE-2024-3651",
				"Link": "https://nvd.nist.gov/vuln/detail/CVE-2024-3651"
			}
		]
	},
	"Metadata": [
		{
			"Text": "graaff",
			"Tag": "requester",
			"Timestamp": "2024-12-11T09:59:38.412294Z"
		},
		{
			"Text": "graaff",
			"Tag": "submitter",
			"Timestamp": "2024-12-11T09:59:38.415710Z"
		}
	]
}
