{
	"ID": "202409-12",
	"Title": "pypy, pypy3: Multiple Vulnerabilities",
	"Synopsis": "Multiple vulnerabilities have been discovered in pypy and pypy3, the worst of which could lead to arbitrary code execution.",
	"Product": {
		"Text": "pypy,pypy-exe,pypy-exe-bin,pypy3",
		"Type": "ebuild"
	},
	"Announced": "2024-09-22",
	"Revised": {
		"Text": "2024-09-22",
		"Count": "1"
	},
	"Bug": [
		"741496",
		"741560",
		"774114",
		"782520"
	],
	"Access": "local",
	"Affected": {
		"Package": [
			{
				"Name": "dev-python/pypy",
				"Auto": "yes",
				"Arch": "*",
				"Unaffected": [
					{
						"Text": "7.3.3_p37_p1-r1",
						"Range": "ge",
						"Slot": ""
					}
				],
				"Vulnerable": [
					{
						"Text": "7.3.3_p37_p1-r1",
						"Range": "lt",
						"Slot": ""
					}
				]
			},
			{
				"Name": "dev-python/pypy-exe",
				"Auto": "yes",
				"Arch": "*",
				"Unaffected": [
					{
						"Text": "7.3.2",
						"Range": "ge",
						"Slot": ""
					}
				],
				"Vulnerable": [
					{
						"Text": "7.3.2",
						"Range": "lt",
						"Slot": ""
					}
				]
			},
			{
				"Name": "dev-python/pypy-exe-bin",
				"Auto": "yes",
				"Arch": "*",
				"Unaffected": null,
				"Vulnerable": [
					{
						"Text": "7.3.2",
						"Range": "lt",
						"Slot": ""
					}
				]
			},
			{
				"Name": "dev-python/pypy3",
				"Auto": "yes",
				"Arch": "*",
				"Unaffected": [
					{
						"Text": "7.3.3_p37_p1-r1",
						"Range": "ge",
						"Slot": ""
					}
				],
				"Vulnerable": [
					{
						"Text": "7.3.3_p37_p1-r1",
						"Range": "lt",
						"Slot": ""
					}
				]
			}
		],
		"Service": {
			"Text": "",
			"Type": "",
			"Fixed": ""
		}
	},
	"Background": {
		"Text": "\n        <p>A fast, compliant alternative implementation of the Python language.</p>\n    "
	},
	"Description": {
		"Text": "\n        <p>Multiple vulnerabilities have been discovered in pypy. Please review the CVE identifiers referenced below for details.</p>\n    "
	},
	"Impact": {
		"Type": "normal",
		"Text": "\n        <p>Please review the referenced CVE identifiers for details.</p>\n    "
	},
	"Workaround": {
		"Text": "\n        <p>There is no known workaround at this time.</p>\n    "
	},
	"Resolution": {
		"Text": "\n        \n        \n        \n        \n        \n        \n        \n    ",
		"P": [
			{
				"Text": "All pypy users should upgrade to the latest version:",
				"URI": {
					"Text": "",
					"Link": ""
				},
				"Br": null,
				"I": null,
				"Code": "",
				"P": ""
			},
			{
				"Text": "All pypy3 users should upgrade to the latest version:",
				"URI": {
					"Text": "",
					"Link": ""
				},
				"Br": null,
				"I": null,
				"Code": "",
				"P": ""
			}
		],
		"Code": [
			"\n          # emerge --sync\n          # emerge --ask --oneshot --verbose \">=dev-python/pypy-7.3.3_p37_p1-r1\"\n          # emerge --ask --oneshot --verbose \">=dev-python/pypy-exe-7.3.2\"\n          # emerge --ask --oneshot --verbose \">=dev-python/pypy-exe-bin-7.3.2\"\n        ",
			"\n          # emerge --sync\n          # emerge --ask --oneshot --verbose \">=dev-python/pypy3-7.3.3_p37_p1-r1\"\n        "
		]
	},
	"References": {
		"URI": [
			{
				"Text": "CVE-2020-27619",
				"Link": "https://nvd.nist.gov/vuln/detail/CVE-2020-27619"
			}
		]
	},
	"Metadata": [
		{
			"Text": "graaff",
			"Tag": "requester",
			"Timestamp": "2024-09-22T06:59:11.659897Z"
		},
		{
			"Text": "graaff",
			"Tag": "submitter",
			"Timestamp": "2024-09-22T06:59:11.662062Z"
		}
	]
}
